### ISSUE TITLE
大哥会提示一个反射的类转换错误，能不能看下

### ISSUE THREAD

**Issue by dukesk** [qiaoyhh/AndroidProjectHelper#4]
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
at qyh.androidprojecthelper.utils.TUtil.getT(TUtil.java:12)
at qyh.androidprojecthelper.base.BaseActivity.onCreate(BaseActivity.java:72)
at qyh.androidprojecthelper.MainActivity.onCreate(MainActivity.java:76)

**Comment by my29** [comment]
解决了吗？
